# Generated by Django 3.2.14 on 2022-07-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220710_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergoal',
            name='brand',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='api.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customergoal',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.promotion'),
        ),
        migrations.AlterField(
            model_name='customergoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user'),
        ),
    ]
